version: 2

updates:
- package-ecosystem: 'npm'
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  assignees:
  - tobibechtold
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  assignees:
  - pfichtner
